watermark_captions = {
    "default": {
        "font_size": 40,
        "color": "white",
        "bg_color": "transparent",
        "position": ("center", "bottom"),
    },
    "brand": {
        "font_size": 40,
        "color": "white",
        "bg_color": "transparent",
        "position": ("center", "top"),
    },
}

captions = {
    "1": {
        "font_size": "dynamic",
        "color": "white",
        "font": "NimbusSans-Bold",
        "stroke_color": "black",
        "stroke_width": 2,
        "shadow_color": "black",
        "shadow_offset": (3, 3),
        "casing": "upper",
    },
    "2": {
        "font_size": "dynamic",
        "color": "white",
        "font": "AvantGarde-Demi",
        "stroke_color": "black",
        "stroke_width": 2,
        "shadow_color": "black",
        "shadow_offset": (3, 3),
        "casing": "lower",
    },
    "3": {
        "font_size": "dynamic",
        "color": "black",
        "font": "Bookman-Demi",
        "casing": "upper",
        "bg_color": "yellow",
    },
    "4": {
        "font_size": "dynamic",
        "color": "yellow",
        "font": "NimbusSans-Bold",
        "stroke_color": "black",
        "stroke_width": 2,
        "shadow_color": "black",
        "shadow_offset": (3, 3),
        "casing": "upper",
    },
    "5": {
        "font_size": "dynamic",
        "color": "black",
        "font": "NimbusSans-Bold",
        "casing": "lower",
        "bg_color": "yellow",
    },
    "6": {
        "font_size": "dynamic",
        "color": "black",
        "font": "Humor-Sans",
        "casing": "upper",
        "bg_color": "yellow",
    },
    "7": {
        "font_size": "dynamic",
        "color": "yellow",
        "font": "Liberation-Mono-Bold",
        "stroke_color": "black",
        "stroke_width": 2,
        "shadow_color": "black",
        "shadow_offset": (3, 3),
        "casing": "lower",
    },
    "8": {
        "font_size": "dynamic",
        "color": "white",
        "font": "Liberation-Mono-Bold",
        "stroke_color": "black",
        "stroke_width": 2,
        "shadow_color": "black",
        "shadow_offset": (3, 3),
        "casing": "upper",
    },
    "9": {
        "font_size": "dynamic",
        "color": "white",
        "font": "Nimbus-Mono-L-Bold",
        "stroke_color": "black",
        "stroke_width": 2,
        "shadow_color": "black",
        "shadow_offset": (3, 3),
        "casing": "upper",
    },
    "10": {
        "font_size": "dynamic",
        "color": "white",
        "font": "URW-Bookman-Demi",
        "stroke_color": "black",
        "stroke_width": 2,
        "shadow_color": "black",
        "shadow_offset": (3, 3),
        "casing": "upper",
    },
    "11": {
        "font_size": "dynamic",
        "color": "white",
        "font": "URW-Bookman-Demi",
        "stroke_color": "black",
        "stroke_width": 2,
        "shadow_color": "black",
        "shadow_offset": (3, 3),
        "casing": "lower",
    },
    "12": {
        "font_size": "dynamic",
        "color": "white",
        "font": "Humor-Sans",
        "stroke_color": "black",
        "stroke_width": 2,
        "shadow_color": "black",
        "shadow_offset": (3, 3),
        "casing": "upper",
    },
}

caption_positions = {
    "1": {"text": "Top", "id": "1"},
    "2": {"text": "Center", "id": "2"},
    "3": {"text": "Bottom", "id": "3"},
}
